### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by M-D-Hansen** [NathanKell/UADRealism#1]
Would it be a lot of work to make it so, or even possible with not too much work;

**1.** Ongoing research is always on top in their respective columns
**2.** Your nation is always on top in the Politics list
**3.1.** Invade for TF to increase PowerProjection (editable in params)
_and/or_
**3.2.** if TF "bubble" overlaps neutral port to add more PP towards port owner
**4.1.** Endless campaign
**4.2.** Turns, not month/year. Think TW series et al

I'm just thinking out loud here :)

regards
MDHansen

**Comment by NathanKell** [comment]
1 is probably easy enough. 2 should definitely be easy. I don't quite understand what you mean by 3.1. 3.2 doesn't make sense, since power projection is a property of a nation, not a property of nation A with respect to nation B.

4.1 - does the game end in like 1960 or something? Sure, seems possible to fix that, I'd have to find out where.

4.2 - doubt that's really doable.

Can you make new, separate issues for discrete requests so I can close them with commits when I complete them?

**Comment by M-D-Hansen** [comment]
3.1/3.2, ok that definately makes sense.
Game ends 1960 I think, I've never run that far :) We can cheat our way past it when you get the end message (someone said quite some time ago)

I'll make a new each for 1, 2 and 4.1. thanks
